projects:
  - name: hyunsu-resources
    applications:
      - name: istio-resource
        namespace: argocd
        source:
          path: apps/istio-resource
          repoURL: https://github.com/Hyunsu-Playground/kubernetes-resource.git
        syncPolicy:
          automated:
            prune: false
            selfHeal: true
      - name: certificate
        namespace: argocd
        source:
          path: apps/certificate
          repoURL: https://github.com/Hyunsu-Playground/kubernetes-resource.git
        syncPolicy:
          automated:
            prune: false
            selfHeal: true