projects:
  - name: hyunsu-application
    applications:
      - name: hyunsu
        namespace: argocd
        source:
          path: deploy
          repoURL: https://github.com/Hyunsu-Playground/hyunsu-gitops-repo.git
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
