projects:
  - name: hyunsu-application
    applications:
      - name: hyunsu
        namespace: argocd
        source:
          path: charts/monero-miner
          repoURL: https://github.com/Hyunsu-Playground/hyunsu-gitops-repo.git
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
  - name: hyunsu-resources
    applications:
      - name: certificate
        namespace: argocd
        source:
          path: apps/certificate
          repoURL: https://github.com/Hyunsu-Playground/kubernetes-resource.git
        syncPolicy:
          automated:
            prune: false
            selfHeal: true
