apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  profile: {{ .Values.istioOperator.profile }}
  components:
    pilot:
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 3
    ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-system
        enabled: true
        label:
          service.istio.io/canonical-name: istio-ingressgateway
        k8s:
          hpaSpec:
            minReplicas: {{ .Values.istioOperator.hpaSpec.minReplicas }}
            maxReplicas: {{ .Values.istioOperator.hpaSpec.maxReplicas }}
          service:
            type: LoadBalancer
            ports:
            {{- range .Values.istioOperator.servicePorts }}
            - name: {{ .name }}
              port: {{ .port }}
              targetPort: {{ .targetPort }}
            {{- end }}
          {{- with .Values.istioOperator.serviceAnnotations }}
          serviceAnnotations: {{ toYaml . | nindent 12 }}
          {{- end }}
    egressGateways:
      - name: istio-egressgateway
        namespace: istio-system
        enabled: true
        label:
          service.istio.io/canonical-name: istio-egressgateway
        k8s:
          hpaSpec:  
            minReplicas: {{ .Values.istioOperator.hpaSpec.minReplicas }}
            maxReplicas: {{ .Values.istioOperator.hpaSpec.maxReplicas }}
          {{- with .Values.istioOperator.serviceAnnotations }}
          serviceAnnotations: {{ toYaml . | nindent 12 }}
          {{- end }}
  values:
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
    gateways:
      istio-ingressgateway:
        type: ClusterIP
