ingressGateway:
  servers:
  - hosts:
      - '*'
    port:
      name: https-hyunsu
      number: 80
      protocol: HTTP

virtualServices:
  - name: argocd-server
    host: '*'
    destination:
      host: argocd-server.argocd.svc.cluster.local
      port: 80