ingressGateway:
  servers:
  - hosts:
      - '*.hyunsu.site'
    port:
      name: https-hyunsu
      number: 80
      protocol: HTTP

virtualServices:
  - name: argocd-server
    host: argo-cd.hyunsu.site
    destination:
      host: argocd-server.argocd.svc.cluster.local
      port: 80